# Generated by Django 3.2.9 on 2021-11-23 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='orders.order'),
        ),
    ]
