version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: always

  redis:
    restart: always
    container_name: flower_shop_redis
    image: redis:alpine
  celery:
    container_name: flower_shop_celery
    command: celery -A flower_shop worker -l info
    build: ./
    volumes:
      - .:/code
    depends_on:
      - redis
      - web
